version: '3'

services:
  database:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
